config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_for :users  

  root 'home#index'
  get 'home/interfaces' => 'home#interfaces'
  get 'home/interface_info' => 'home#interface_info'

  # require 'sidekiq/web'
  # mount sidekiq::web => '/sidekiq'

  namespace :backend do
    root 'groups#index'
    resources :groups do
      resources :interfaces
    end
    resources :interfaces do
      resources :interface_params, :interface_responses
    end
    resources :members do
      put :add_group_member
    end
    resources :groups_members, only: [:index, :create, :destroy]
    resources :users
    resources :roles
    resources :users_roles, only: [:create]

    require 'sidekiq/web'
    mount Sidekiq::Web => 'sidekiq'

  end
end

app/views/common/_backend_body.html.erb
<div class="col-md-9 backend_body">
    <div class="row">
       <%= yield %>
    </div>
</div>

app/views/common/_backend_menu.html.erb
<div class="col-md-2 backend_menu">
  <ul class="nav nav-pills nav-stacked">
    <li class="<%= 'active' if request.url.include? 'group' %>">
      <%= link_to '品牌管理', backend_groups_path %>  
    </li>
    <li class="<%= 'active' if request.url.include? 'members' %>">
      <%= link_to '接口调用者管理', backend_members_path %>
    </li>
    <% if current_user.has_role? :admin %>
    <li class="<%= 'active' if request.url.include? 'users' %>">
      <%= link_to '用户管理', backend_users_path %>
    </li>
    <li class="<%= 'active' if request.url.include? 'roles' %>">
      <%= link_to '角色管理', backend_roles_path %>
    </li>
    <% end %>
  </ul>
</div>



app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2017 dodoliu
    <br>Design by <a href="http://dodoliu.github.io/" target=_new>dodoliu</a>
  </p>
</footer>

app/views/common/_front_body.html.erb
<div class="col-md-9 backend_body" id="vue_div">
    <div class="row">
       <%= yield %>
    </div>
</div>

app/views/common/_front_menu.html.erb
<div class="col-md-2 backend_menu">
<div class="panel-group" id="accordion">
<% @groups.each do |g| %>
   <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" 
                href="#collapse<%= g.id %>">
                <%= g.group_name %>
                </a>
            </h4>
        </div>
        <div id="collapse<%= g.id %>" class="panel-collapse collapse in">
            <div class="panel-body">
                  <ul class="nav nav-pills nav-stacked">
                    <% @interfaces.each do |i| %>
                    <% if i.group_id.eql?(g.id) %>
                    <li>
                    <%= link_to i.interface_name, 'javascript:void(0)', 'v-on:click': 'get_interface', 'data-interfacesid': i.sid %>
                    </li>
                    <% end %>
                    <% end %>
                  </ul>
            </div>
        </div>
    </div>
<% end %>
</div>
</div>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
    <div class="navbar-header">
    <%= link_to 'API文档在线管理系统', backend_groups_path, class: 'navbar-brand' %>
    </div>
    <div>
        <ul class="nav navbar-nav" style="float:right;">
            <li class="dropdown">
                <% if current_user %>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <%= current_user.display_name || current_user.email %>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="#">基本信息</a></li>
                    <li>
                    <%= link_to '退出登陆', destroy_user_session_path, :method => 'delete' %>
                    </li>
                </ul>
                <% end %>
            </li>
        </ul>
    </div>
    </div>
</nav>

app/views/common/_welcome.html.erb
  <% if user_signed_in? %> <!-- Provided by devise -->
    <div style="float:right">
      <%= current_user.email %> |
      <%= link_to '用戶信息', edit_user_registration_path %> |
      <%= link_to '退出登錄', destroy_user_session_path, :method => :delete %> |
    </div>
    <% end %>
    <% unless user_signed_in? %>
    <div style="float:right">
      <%= link_to '注冊', new_user_registration_path %> |
      <%= link_to '登錄', new_user_session_path %>
    </div>
<% end %>
</div>