config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_for :users  

  root 'home#index'
  get 'home/interfaces' => 'home#interfaces'
  get 'home/interface_info' => 'home#interface_info'

  # require 'sidekiq/web'
  # mount sidekiq::web => '/sidekiq'

  namespace :backend do
    root 'groups#index'
    resources :groups do
      resources :interfaces
    end
    resources :interfaces do
      resources :interface_params, :interface_responses
    end
    resources :members do
      put :add_group_member
    end
    resources :groups_members, only: [:index, :create, :destroy]
    resources :users
    resources :roles
    resources :users_roles, only: [:create]

    require 'sidekiq/web'
    mount Sidekiq::Web => 'sidekiq'

  end
end

app/views/layouts/application.html.erb
<!-- <!DOCTYPE html> -->
<html>
  <head>
    <title>API文档在线管理系统</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'devise_style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'front', 'data-turbolinks-track': 'reload' %>
    <script type='text/javascript'>
      window.urls = {
        home_interface: '<%= home_interface_info_path %>'
      }
    </script>
  </head>
  <body>
    <div class="container-fluid" id='vue_div'>
      <%= render "common/navbar" %>
      <% if request.url.include?('home/interfaces') %>
      <%= render "common/front_menu" %>
      <%= render "common/front_body" %>      
      <% else %>
      <div id="div_notice_alert">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
        <%= yield %>
      <% end %>
    </div>
    <%= render "common/footer" %>
  </body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>API文档在线管理系统</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type='text/javascript'>
      window.urls = {
        groups_json: '/backend/groups.json',        
        groups_members: '<%= backend_groups_members_path %>',
        home_index: '<%= home_interfaces_path %>',
        add_role: '<%= backend_users_roles_path %>'
      }
    </script>
  </head>
  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/backend_menu" %>
      <%= render "common/backend_body" %>
    </div>
    <%= render "common/footer" %>
  </body>
</html>